### ISSUE TITLE
ImportError: cannot import name 'plyutils'

### ISSUE THREAD

**Issue by cuixin1992** [TimoBolkart/TF_FLAME#57]
Hi, thank you for your great work. But I got a problem when I run your code. Could you help me with it? Thank you very much.

I run the code using the following order.
python sample_FLAME.py --option sample_FLAME --model_fname './models/generic_model.pkl' --num_samples 5 --out_path './FLAME_samples' --visualize False

I got the following error. 
2022-01-06 21:05:24.843794: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
Traceback (most recent call last):
  File "sample_FLAME.py", line 114, in <module>
    main(args)
  File "sample_FLAME.py", line 101, in main
    sample_FLAME(args.model_fname, int(args.num_samples), args.out_path, str2bool(args.visualize), sample_VOCA_template=False)
  File "sample_FLAME.py", line 92, in sample_FLAME
    sample_mesh.write_ply(out_fname)
  File "D:\CUIXIN\01_HumanModelTemplate\TF_FLAME-master\psbody\mesh\mesh.py", line 476, in write_ply
    serialization.write_ply(self, filename, flip_faces, ascii, little_endian, comments)
  File "D:\CUIXIN\01_HumanModelTemplate\TF_FLAME-master\psbody\mesh\serialization\serialization.py", line 214, in write_ply
    from psbody.mesh.serialization import plyutils
ImportError: cannot import name 'plyutils'

**Comment by pfeducode** [comment]
> 

do you solve this problem？

**Comment by arintharoza** [comment]
Same problem here. Any help please? It seems that there is no plyutils.py file in the serialization directory!
